version: '3.8'

services:

  db:
    image: postgres:${VERSION_POSTGRES}
    restart: always
    #command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - dev
  pgadmin4:
    image: elestio/pgadmin:${PGADMIN_VERSION}
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./rename:/pgadmin4/rename
    networks:
      - dev
  www:
    build: docker
    container_name: Project_name
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

  mailcatcher:
    container_name: customName_mailcatcher
    image: jeanberu/mailcatcher:latest
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - dev
networks:
  dev:

volumes:
  db-data:
